AcunMedyaAkademiAgency/Entities/Notification.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AcunMedyaAkademiAgency.Entities
{
    public class Notification
    {
        public int NotificationID { get; set; }
        public string NameSurname { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    }
}

AcunMedyaAkademiAgency/Controllers/FeatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcunMedyaAkademiAgency.Context;
using AcunMedyaAkademiAgency.Entities;


namespace AcunMedyaAkademiAgency.Controllers
{
    public class FeatureController : Controller
    {
        // GET: Feature
        AgencyContext context = new AgencyContext();
        public ActionResult FeatureList()
        {
            var value = context.Features.ToList();
            return View(value);
        }
        [HttpGet]
        public ActionResult CreateFeature()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateFeature(Feature feature)
        {
            context.Features.Add(feature);
            context.SaveChanges();
            return RedirectToAction("FeatureList");
        }

        public ActionResult DeleteFeature(int id)
        {
            var value = context.Features.Find(id);
            context.Features.Remove(value);
            context.SaveChanges();

            return RedirectToAction("FeatureList");
        }
        [HttpGet]
        public ActionResult UpdateFeature(int id)
        {
            var value = context.Features.Find(id);
            return View(value);
        }
        [HttpPost]
        public ActionResult UpdateFeature(Feature feature)
        {
            var value = context.Features.Find(feature.FeatureID);
            value.Title = feature.Title;
            value.Description = feature.Description;
            value.ImageUrl = feature.ImageUrl;

            context.SaveChanges();

            return RedirectToAction("FeatureList");
        }
    }
}

AcunMedyaAkademiAgency/Controllers/NotificationController.cs
using AcunMedyaAkademiAgency.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcunMedyaAkademiAgency.Entities;

namespace AcunMedyaAkademiAgency.Controllers
{
    public class NotificationController : Controller
    {
        AgencyContext context = new AgencyContext();
        public ActionResult NotificationList()
        {
            var values = context.Notifications.ToList();
            return View(values);
        }
        [HttpGet]
        public ActionResult CreateNotification()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateNotification(Notification notification)
        {
            context.Notifications.Add(notification);
            context.SaveChanges();

            return RedirectToAction("NotificationList");
        }
        public ActionResult DeleteNotification(int id)
        {
            var value = context.Notifications.Find(id);
            context.Notifications.Remove(value);
            context.SaveChanges();
            return RedirectToAction("NotificationList");
        }
        [HttpGet]
        public ActionResult UpdateNotification(int id)
        {
            var value = context.Notifications.Find(id);
            return View(value);
        }
        [HttpPost]
        public ActionResult UpdateNotification(Notification notification)
        {
            var value = context.Notifications.Find(notification.NotificationID);
            value.NameSurname = notification.NameSurname;
            value.Description = notification.Description;
            value.ImageUrl = notification.ImageUrl;
            context.SaveChanges();
            return RedirectToAction("NotificationList");
        }
    }
}

AcunMedyaAkademiAgency/Views/Notification/CreateNotification.cshtml
@{
    ViewBag.Title = "CreateNotification";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<h2>Bildirim Ekleme Sayfası</h2>

<form method="post">
    <label>Ad Soyad</label>
    <input type="text" class="form-control" name="NameSurname" />
    <br />
    <label>Bildirim Açıklaması</label>
    <textarea rows="4" class="form-control" name="Description"></textarea>
    <br />
    <label>Resim Url</label>
    <input type="text" class="form-control" name="ImageUrl" />
    <br />
    <button class="btn btn-danger">Bildirimi Kaydet</button>
    <a href="@Url.Action("NotificationList", "Notification")" class="btn btn-outline-dark">Vazgeç</a>
</form>

AcunMedyaAkademiAgency/Views/Notification/NotificationList.cshtml
@model List<AcunMedyaAkademiAgency.Entities.Notification>
@{
    ViewBag.Title = "NotificationList";
    Layout = "~/Views/AdminLayout/Index.cshtml";
    int count = 0;
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Bidirimler Sayfası</h4>
            <p class="card-description">
                Bildirimler ile ilgili işlemleri buradan yapabilirsiniz.
            </p>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ad Soyad</th>
                            <th>Açıklaması</th>
                            <th>Resim</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            count++;
                            <tr>
                                <td>@count</td>
                                <td>@item.NameSurname</td>
                                <td>@item.Description</td>
                                <td><img src="@item.ImageUrl" style="width:75px;height:75px;" alt="Hizmet Görseli" /></td>
                                <td><a class="btn btn-danger" href="/Notification/DeleteNotification/@item.NotificationID"><i class="fa fa-trash"></i> Sil</a></td>
                                <td><a class="btn btn-success" href="/Notification/UpdateNotification/@item.NotificationID"><i class="fa fa-pencil"></i> Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
                <br />
                <a href="/Notification/CreateNotification" class="btn btn-info"><i class="mdi mdi-file-check btn-icon-append">Bildirim Ekle</i></a>
            </div>
        </div>
    </div>
</div>

AcunMedyaAkademiAgency/Views/Notification/UpdateNotification.cshtml
@model  AcunMedyaAkademiAgency.Entities.Notification
@{
    ViewBag.Title = "UpdateNotification";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Bildirim Güncelleme Sayfası</h4>
            <p class="card-description">Bildirim ile ilgili güncelleme işlemlerini buradan yapabilirsiniz.</p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label for="exampleInputName1">#</label>
                    @Html.TextBoxFor(x => x.NotificationID, new { @class = "table table-bordered", @readonly = "readonly" })
                </div>
                <div class="form-group">
                    <label for="exampleInputName1">Ad Soyad</label>
                    @Html.TextBoxFor(x => x.NameSurname, new { @class = "table table-bordered" })
                </div>
                <div class="form-group">
                    <label for="exampleTextarea1">Bildirim Açıklaması</label>
                    <textarea class="form-control"
                              id="exampleTextarea1"
                              rows="4" name="Description">@Model.Description</textarea>
                </div>
                <div class="form-group">
                    <label for="exampleInputCity1">Bildirim Resim Yolu</label>
                    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "table table-bordered" })
                </div>
                <button type="submit" class="btn btn-primary mr-2"> Güncelle </button>
                <a href="@Url.Action("FeatureList", "Feature")" class="btn btn-outline-dark">Vazgeç</a>
            </form>
        </div>
    </div>
</div>