AcunMedyaAkademiAgency/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcunMedyaAkademiAgency.Context;

namespace AcunMedyaAkademiAgency.Controllers
{
    public class DefaultController : Controller
    {
        AgencyContext context = new AgencyContext();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult ProjectPartial()
        {
            var values = context.Projects.OrderByDescending(x => x.ProjectID).Take(6).ToList();
            return PartialView(values);
        }
        public PartialViewResult ModalPartial()
        {
            var values = context.ProjectDetails.ToList();
            return PartialView(values);
        }
        public PartialViewResult HeaderPartial()
        {
            return PartialView();
        }

        public PartialViewResult NavbarPartial()
        {
            return PartialView();
        }
        public PartialViewResult FeaturePartial()
        {
            var values = context.Features.ToList();
            return PartialView(values);
        }
        public PartialViewResult ServicePartial()
        {
            var values = context.Services.ToList();
            return PartialView(values);
        }
        public PartialViewResult AboutPartial()
        {
            var values = context.Abouts.ToList();
            return PartialView(values);
        }
        public PartialViewResult TeamPartial()
        {
            var values = context.Teams.ToList();
            return PartialView(values);
        }
        public PartialViewResult ClientsPartial()
        {
            return PartialView();
        }
        public PartialViewResult ContactPartial()
        {
            return PartialView();
        }
        public PartialViewResult FooterPartial()
        {
            return PartialView();
        }
        public PartialViewResult SocialMediaPartial()
        {
            var values = context.SocialMedias.ToList();
            return PartialView(values);
        }
        public PartialViewResult NavigationPartial()
        {
            return PartialView();
        }
        public PartialViewResult GoogleMapsPartial()
        {
            return PartialView();
        }



    }
}

AcunMedyaAkademiAgency/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcunMedyaAkademiAgency.Entities;
using AcunMedyaAkademiAgency.Context;

namespace AcunMedyaAkademiAgency.Controllers
{
    public class MessageController : Controller
    {
        AgencyContext context = new AgencyContext();

        public ActionResult MessageList(string searchText)
        {
            List<Message> values = new List<Message>();
            if (!string.IsNullOrEmpty(searchText))
            {
                values = context.Messages.Where(x => x.NameSurname.Contains(searchText)).ToList();
            }
            else
            {
                values = context.Messages.ToList();
            }

            return View(values);
        }
        [HttpPost]
        public ActionResult UpdateIsRead(int messageId, bool isRead)
        {
            var message = context.Messages.Find(messageId);
            if (message != null)
            {
                message.IsRead = isRead;
                context.SaveChanges();
            }
            return Json(new { success = true });
        }

        public ActionResult DeleteMessage(int id)
        {
            var value = context.Messages.Find(id);
            context.Messages.Remove(value);
            context.SaveChanges();
            return RedirectToAction("MessageList");
        }

        [HttpGet]
        public ActionResult CreateMessage()
        {
            return View();
        }

 
        [HttpPost]
        public ActionResult CreateMessage(Message message)
        {
            message.IsRead = false; 
            message.SendDate = DateTime.Now; 
            context.Messages.Add(message);
            context.SaveChanges();
            return RedirectToAction("MessageList");
        }
    }
}

AcunMedyaAkademiAgency/Views/Default/AboutPartial.cshtml
@model List<AcunMedyaAkademiAgency.Entities.About>
@{
    var count = 2;
}
<section class="page-section" id="about">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Hakkımızda</h2>
            <h3 class="section-subheading text-muted">Bizler kimiz</h3>
        </div>
        <ul class="timeline">
            @foreach (var item in Model)
            {
                if (count % 2 == 0)
                {
                    <li>
                        <div class="timeline-image"><img class="rounded-circle" src="@item.ImageUrl" style="width: 100%;height: 100%;object-fit: cover;" /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="subheading">@item.Title</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">@item.Description</p></div>
                        </div>
                    </li>
                }

                else
                {
                    <li class="timeline-inverted">
                        <div class="timeline-image"><img class="rounded-circle" src="@item.ImageUrl" width="160px" height="160px" /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="subheading">@item.Title</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">@item.Description</p></div>
                        </div>
                    </li>
                }
                count++;
            }
        </ul>
    </div>
</section>

AcunMedyaAkademiAgency/Views/Default/ClientsPartial.cshtml
<div class="py-5">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-3 col-sm-6 my-3">
                <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="assets/img/logos/microsoft.svg" alt="..." /></a>
            </div>
            <div class="col-md-3 col-sm-6 my-3">
                <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="assets/img/logos/google.svg" alt="..." /></a>
            </div>
            <div class="col-md-3 col-sm-6 my-3">
                <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="assets/img/logos/facebook.svg" alt="..." /></a>
            </div>
            <div class="col-md-3 col-sm-6 my-3">
                <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="assets/img/logos/ibm.svg" alt="..." /></a>
            </div>
        </div>
    </div>
</div>

AcunMedyaAkademiAgency/Views/Default/ContactPartial.cshtml
﻿<section class="page-section" id="contact">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Bizimle Iletişime Geçin</h2>
            <h3 class="section-subheading text-muted">Görüşleriniz ve Önerilerin Bizim İçin Değerli</h3>
        </div>
        <!-- * * * * * * * * * * * * * * *-->
        <!-- * * SB Forms Contact Form * *-->
        <!-- * * * * * * * * * * * * * * *-->
        <!-- This form is pre-integrated with SB Forms.-->
        <!-- To make this form functional, sign up at-->
        <!-- https://startbootstrap.com/solution/contact-forms-->
        <!-- to get an API token!-->
        <form method="post" action="@Url.Action("SendMessage", "Message")" id="contactForm" data-sb-form-api-token="API_TOKEN">
            <div class="row align-items-stretch mb-5">
                <div class="col-md-6">
                    <div class="form-group">
                        <!-- Name input-->
                        <input class="form-control" id="name" name="NameSurname" type="text" placeholder="İsim Soyisim *" data-sb-validations="required" />
                        <div class="invalid-feedback" data-sb-feedback="name:required">İsim Boş Bırakılamaz</div>
                    </div>
                    <div class="form-group">
                        <!-- Email address input-->
                        <input class="form-control" id="email" name="Email" type="email" placeholder="Mailiniz *" data-sb-validations="required,email" />
                        <div class="invalid-feedback" data-sb-feedback="email:required">Mail Adresi Zorunludur</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Mail Mevcut Değil</div>
                    </div>
                    <div class="form-group mb-md-0">
                        <!-- Title input-->
                        <input class="form-control" id="message" name="Title" type="text" placeholder="Mesaj Başlığı *" data-sb-validations="required" />
                        <div class="invalid-feedback" data-sb-feedback="message:required">Başlık Boş Bırakılamaz</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group form-group-textarea mb-md-0">
                        <!-- Message input-->
                        <textarea class="form-control" id="message" name="Description" placeholder="Mesajınız *" data-sb-validations="required"></textarea>
                        <div class="invalid-feedback" data-sb-feedback="message:required">Mesaj Boş Bırakılamaz</div>
                    </div>
                </div>
            </div>
            <!-- Submit success message-->
            @if (TempData["successMessage"] != null)
            {
                <div class="text-center text-white mb-3">
                    <div class="fw-bolder">@TempData["successMessage"]</div>
                    <br />
                </div>
            }
            <!-- Submit error message-->
            @if (TempData["errorMessage"] != null)
            {
                <div class="text-center text-danger mb-3">
                    <div class="fw-bolder">@TempData["errorMessage"]</div>
                    <br />
                </div>
            }
            <!-- Submit Button-->
            <div class="text-center"><button class="btn btn-primary btn-xl text-uppercase" id="submitButton" type="submit">GÖNDER</button></div>
        </form>
    </div>
</section>

AcunMedyaAkademiAgency/Views/Default/FeaturePartial.cshtml
@model List<AcunMedyaAkademiAgency.Entities.Feature>
<header class="masthead">
    <div class="container">
        @foreach (var item in Model)
        {
            <div class="masthead-subheading">@item.Title</div>
            <div class="masthead-heading text-uppercase">@item.Description</div>
        }
        <a class="btn btn-primary btn-services btn-xl" style="position: relative; z-index: 2;" href="#services">Daha Fazlası İçin</a>
    </div>
</header>

AcunMedyaAkademiAgency/Views/Default/FooterPartial.cshtml
<footer class="footer py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-3 text-lg-start">Copyright &copy; Your Website 2021</div>
            <div class="col-lg-3 text-lg-start">Distributed By <a href="https://themewagon.com/">Themewagon</a></div>
            <div class="col-lg-3 my-3 my-lg-0">
                <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
            </div>
            <div class="col-lg-3 text-lg-end">
                <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
            </div>
        </div>
    </div>
</footer>

AcunMedyaAkademiAgency/Views/Default/GoogleMapsPartial.cshtml
<div style="display: flex; width: 100%; height: 500px; background-color: #FFC800;">
    <div style="width: 40%; padding: 20px; display: flex; align-items: center; justify-content: center; color: #eee; text-align: center;">
        <div>
            <h2>Konumumuz</h2>
            <p>Can PARMAK, Beykoz Üniversitesi, İstanbul</p>
            <p>E-posta: mcanparmak@gmail.com</p>
        </div>
    </div>
    <div style="width: 60%;">
        <iframe width="100%"
                height="100%"
                frameborder="0"
                style="border: 0"
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3006.9525394311427!2d29.094326499999998!3d41.0918836!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cacbb9c81ca2bd%3A0xfebdb3183f0e8701!2sBeykoz%20%C3%9Cniversitesi%20Lisans%20Yerle%C5%9Fkesi!5e0!3m2!1str!2str!4v1741905696712!5m2!1str!2str" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </iframe>
    </div>
</div>

AcunMedyaAkademiAgency/Views/Default/HeaderPartial.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Agency Web Site</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/Templates/agency/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Templates/agency/css/styles.css" rel="stylesheet" />
</head>

AcunMedyaAkademiAgency/Views/Default/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
@Html.Partial("/Views/Default/HeaderPartial.cshtml")
<body id="page-top">
    <!-- Navigation-->
    @Html.Action("NavigationPartial", "Default")
    <!-- Masthead-->
    @Html.Action("FeaturePartial", "Default")
    <!-- Services-->
    @Html.Action("ServicePartial", "Default")
    <!-- Portfolio Grid-->
    @Html.Action("ProjectPartial", "Default")
    <!-- About-->
    @Html.Action("AboutPartial", "Default")
    <!-- Team-->
    @Html.Action("TeamPartial", "Default")
    <!-- Clients-->
    @Html.Partial("/Views/Default/ClientsPartial.cshtml")
    <!-- Contact-->
    @Html.Action("ContactPartial", "Default")
    <!-- Map-->
    @Html.Partial("/Views/Default/GoogleMapsPartial.cshtml")
    <!-- Footer-->
    @Html.Action("FooterPartial", "Default")
    <!-- Portfolio Modals-->
    <!-- Portfolio item 1 modal popup-->
    <!-- Portfolio item 2 modal popup-->
    @Html.Action("ModalPartial", "Default")
    <!-- Portfolio item 3 modal popup-->
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="/Templates/agency/js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

AcunMedyaAkademiAgency/Views/Default/ModalPartial.cshtml
@model List<AcunMedyaAkademiAgency.Entities.ProjectDetail>
@foreach (var item in Model)
{
    <div class="portfolio-modal modal fade" id="portfolioModal2-@item.ProjectID" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="close-modal" data-bs-dismiss="modal"><img src="/Templates/agency/assets/img/close-icon.svg" alt="Close modal" /></div>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="modal-body">
                                <!-- Project details-->
                                <h2 class="text-uppercase">@item.Projects.Title</h2>
                                <p class="item-intro text-muted">@item.Title</p>
                                <img class="img-fluid d-block mx-auto" src="@item.Projects.ImageUrl" alt="..." />
                                <p>@item.Description</p>
                                <ul class="list-inline">

                                    <li>
                                        <strong>Kategori:</strong>
                                        @item.Projects.Category.CategoryName
                                    </li>
                                </ul>
                                <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                    <i class="fas fa-times me-1"></i>
                                    Pencereyi Kapat
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

AcunMedyaAkademiAgency/Views/Default/NavbarPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top"><img src="/Templates/agency/assets/img/navbar-logo.svg" alt="..." /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link" href="#services">Hizmetler</a></li>
                <li class="nav-item"><a class="nav-link" href="#portfolio">Projeler</a></li>
                <li class="nav-item"><a class="nav-link" href="#about">Hakkımızda</a></li>
                <li class="nav-item"><a class="nav-link" href="#team">Ekibimiz</a></li>
                <li class="nav-item"><a class="nav-link" href="#contact">İletişim</a></li>
            </ul>
        </div>
    </div>
</nav>

AcunMedyaAkademiAgency/Views/Default/NavigationPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top"><img src="/Templates/agency/assets/img/navbar-logo.svg" alt="..." /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link" href="#services">Hizmetler</a></li>
                <li class="nav-item"><a class="nav-link" href="#portfolio">Projeler</a></li>
                <li class="nav-item"><a class="nav-link" href="#about">Hakkımızda</a></li>
                <li class="nav-item"><a class="nav-link" href="#team">Ekibimiz</a></li>
                <li class="nav-item"><a class="nav-link" href="#contact">İletişim</a></li>
            </ul>
        </div>
    </div>
</nav>

AcunMedyaAkademiAgency/Views/Default/ProjectPartial.cshtml
@model List<AcunMedyaAkademiAgency.Entities.Project>
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Projelerimiz</h2>
            <h3 class="section-subheading text-muted">Alanında uzmanlaşmış kadromuz ile proje bitirme işlemleri ve proje desteği sağlanmaktadır.</h3>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio item 1-->
                    <div class="portfolio-item">
                        <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal2-@item.ProjectID">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="@item.ImageUrl" alt="..." />
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">@item.Title</div>
                            <div class="portfolio-caption-subheading text-muted">@item.Category.CategoryName</div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

AcunMedyaAkademiAgency/Views/Default/SocialMediaPartial.cshtml
@model List<AcunMedyaAkademiAgency.Entities.SocialMedia>
<style>
    .btn-social img {
        max-width: 100%;
        max-height: 100%;
        width: auto;
        height: auto;
    }
</style>

@foreach (var item in Model)
{
    string iconClass = "fas fa-camera"; 

    string iconName = item.Icon?.Trim().ToLower() ?? "";

    if (iconName.Contains("linkedin"))
    {
        iconClass = "fab fa-linkedin";
    }
    else if (iconName.Contains("github"))
    {
        iconClass = "fab fa-github";
    }
    else if (iconName.Contains("instagram"))
    {
        iconClass = "fab fa-globe"; 
    }

    <a class="btn btn-dark btn-social mx-2" href="@item.Url" target="_blank">
        <i class="@iconClass"></i>
    </a>
}

AcunMedyaAkademiAgency/Views/Default/TeamPartial.cshtml
@model List<AcunMedyaAkademiAgency.Entities.Team>
<section class="page-section bg-light" id="team">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Ajansımızın Uzman Kadrosu</h2>
            <h3 class="section-subheading text-muted">Uzman Ekibimizle Geleceği İnşa Ediyoruz</h3>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-4">
                    <div class="team-member text-center">
                        <img class="rounded-circle img-fluid" src="@item.ImageUrl" alt="@item.NameSurname" style="width: 200px; height: 200px; object-fit: cover;" />
                        <h4>@item.NameSurname</h4>
                        <p class="text-muted">@item.Branch.BranchName</p>
                        @Html.Action("SocialMediaPartial", "Default")
                    </div>
                </div>
            }

        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">Projelerinize hayat veriyoruz, hayallerinizi gerçeğe dönüştürüyoruz.</p></div>
        </div>
    </div>
</section>